language: android
# sudo set to required because of an issue with how TravisCI handles builds in Docker containers https://github.com/travis-ci/travis-ci/issues/3695.
# Setting sudo to required prevents Travis from testing the project in a Docker container.
sudo: required
jdk: oraclejdk8
dist: precise

env:
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=20
    - MALLOC_ARENA_MAX=2

android:
  components:
    # tools required
    - tools
    - platform-tools
    - tools
    
    # The BuildTools version used by your project
    - build-tools-26.0.1
    - build-tools-27.0.3
    - build-tools-26.0.2
    - build-tools-25.0.0
    - build-tools-25.0.0
   
    # The SDK version used to compile your projects
    - android-21
    - android-22
    - android-27
    - android-26
    
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22

addons:
  apt_packages:
  - pandoc

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

before_script:
  # Emulator Management: Create, Start and Wait
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"

  - echo "Starting Login MVP Sample ...."
  - cd login-mvp
  - chmod 755 gradlew
  - ls -la
  # This is supposed to run the normal project build
  - travis_wait ./gradlew clean build --stacktrace
  - cd ..

  - echo "Starting Task MVP Sample ...."
  - cd task-mvp-sample
  - chmod 755 gradlew
  - ls -la
  # This is supposed to run the normal project build
  - travis_wait ./gradlew clean test --stacktrace
  - cd ..

  - echo "Starting Notes MVP Sample ...."
  - cd notes-mvp
  - chmod 755 gradlew
  - ls -la
  # This is supposed to run the normal project build
  - travis_wait ./gradlew clean build --stacktrace
  - cd ..

  - echo "Starting Random Quotes MVP Sample ..."
  - cd random-quote-generator-mvp
  - chmod 755 gradlew
  - ls -la
  # Enable the line below once we get all the test passing, currently most of the tests are failing
  # so we'll just if the project compiles
  #Run All tests Unit and Instrumentation
  - travis_wait ./gradlew build --stacktrace
  - cd ..
  
after_failure:
 - pandoc reports/tests/index.html -t plain
